"""initial schema

Revision ID: dff0f68ce05f
Revises: 
Create Date: 2026-08-18 15:39:29.355270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dff0f68ce05f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('a', 'b', name='personrole', native_enum=False, length=8), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_household_id'), ['household_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_by_person_id', sa.Integer(), nullable=True),
    sa.Column('paid_by_person_id', sa.Integer(), nullable=True),
    sa.Column('split_type', sa.Enum('shared', 'personal', name='splittype', native_enum=False, length=16), nullable=False),
    sa.Column('kind', sa.Enum('expense', 'invoice', name='expensekind', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('pending_confirm', 'confirmed', 'rejected', name='expensestatus', native_enum=False, length=24), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=True),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('comida', 'supermercado', 'transporte', 'vivienda', 'servicios', 'salud', 'educacion', 'entretenimiento', 'ropa', 'mascotas', 'otros', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('source_file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['paid_by_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_spent_on'), ['spent_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)

    op.create_table('invoice_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('legal_name', sa.String(length=250), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('authorization_sri', sa.String(length=80), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iva_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iva_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('items_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_details_expense_id'), ['expense_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_details_expense_id'))

    op.drop_table('invoice_details')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_spent_on'))
        batch_op.drop_index(batch_op.f('ix_expenses_household_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_household_id'))

    op.drop_table('persons')
    op.drop_table('households')
    # ### end Alembic commands ###
